config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root "home#index"
  resources :home
  resources :comments
  resources :games
  resources :posts
  resources :users

  get "/games/show/:name" => "games#show", as: "show_game"
  get "/games/results" => "games#result", as: "game_result"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  validates_uniqueness_of :name
  has_many :posts


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    client = Twitch::Client.new client_id: "#{ENV["TWITCH_CLIENT"]}"
    @top_games = client.get_top_games.data
    @top_games_id = []
    @top_games.each do |top_game|
      @top_games_id.push(Game.where(:name =>"#{top_game.name}").first_or_create(:box_art_url => "#{top_game.box_art_url}"))
    end
  end

  def show
    @game = Game.find(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {})
    @post = Post.new
    @posts = @game.posts
    @comment = Comment.new
  end

  def edit
    @game = Game.find(params[:id])
  end

  def destroy
  end

  def update
    @game = Game.find(params[:id])
  end

  def create
    client = Twitch::Client.new client_id: "#{ENV["TWITCH_CLIENT"]}"
    game = client.get_games({name: ["#{params[:name]}"]}).data
    game.each do |game|
      @game = Game.create(name: game.name, box_art_url: game.box_art_url)
    end

    if @game == nil
      flash[:error] = "game does not exist"
      redirect_to games_path
    elsif Game.find_by(name: @game.name)
      game_path_id = Game.find_by(name: @game.name)
      redirect_to game_path(game_path_id)  
    elsif @game.save
      flash[:info] = "successful"
      redirect_to game_path(@game.id)
    else
      flash[:error] = "failed"
      redirect_to games_path
    end
  end

  def new
    @game = Game.new
  end

  def result
    @game = params[:name]
  end

  private

  def game_params
    params.permit(:name)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/index.html.erb
<div class="main">
  <div class="container">
    <h1>GAMES</h1>

    <%= image_tag 'games.jpg', :class => "jumbotron" %>

    <br><br><br>

    <div class="search-container2">
      <%= form_for game_result_path do %>
        <%= text_field_tag :name, params[:name], class: "searchy", placeholder: "Search for a game..."  %>
        <%= button_tag(type: "submit") do %>
          <i class="search-icon" data-feather="search"></i>
        <% end %>
        
      <% end %>
    </div>

<br><br><br><br>
    <h2 class="center-text"> TOP GAMES </h2>

    <div class="gal">
      <% @top_games.each_with_index do |game, index| %>
        <% if game.name == "IRL" || game.name == "Casino" || game.name == "Talk Shows" || game.name == "Creative" || game.name == "Music" %>
          <% next %>
        <% end %>
        <div class="pic">
          <div class="game-title">
            <%= game.name %>
          </div>
          
            <%= link_to image_tag("#{game.box_art_url.gsub("-{width}x{height}","")}"), game_path(@top_games_id[index]), class: "game-pic"%>

        </div>
      <% end %>
    </div>
    
    </div>
  </div>
  

</div>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/result.html.erb
  <div class="main">
    <div class="container">
      <h2 class="head"> <%= @game.name %> </h1>
      <div>
        <img src= <%= @game.box_art_url.gsub("-{width}x{height}","") %> class="main-img">
      </div>
      <h2 class="head">Result Found</h2>
    </div>
  </div>

app/views/games/show.html.erb
<div class="main">
<div class="container">
  <!-- <h1>GAMES</h1> -->
<% if current_user == nil %>
  <h2> You must be signed in to view this page </h2>
  <div class="must-sign">
    <%= link_to "Sign In / Sign Up", user_session_path, :class => "signin_out" %>
  </div>
<% else %>
  <% if @game != nil %>
    <h2 class="head"> <%= @game.name %> </h1>
    <div>
      <img src= <%= @game.box_art_url.gsub("-{width}x{height}","") %> class="main-img">
    </div>

    <div class="content">
      <div class="posts">
        <div class="post">

          <%= form_with model: @post, local: true do |form| %>
          <%= form.hidden_field :user_id, :value => current_user.id %>
          <%= form.hidden_field :game_id, :value => @game.id %>
            <%= form.text_field :title, placeholder: "title", :class => "post-title" %><br />
            <%= form.text_area :content, placeholder: "content", :class => "post-content" %><br/>
            <br><small><em>Powered by Markdown</em></small> <br>
            <%= form.submit "Post", :class => "submit" %>
          <% end %>
        </div>
      </div>
      <div class="reverse-post">
        <% if @posts.count == 0 %>
        <p>There are no posts! Be the first to create a post about this game...</p>
        <% elsif @posts.count != 0 %>

      <% @posts.each do |post| %>

        <div class="user-posts">
          <div class="user-post">
            <%= image_tag User.find(post.user_id).gravatar_url, :class => "mini-avatar" %>
            <span><em><%= User.find(post.user_id).username %></em></span><br/>
            <span><b><%= post.title %></b></span><br>
            <!-- <p><%= post.created_at %></p> -->
            <p><%= @markdown.render(post.content).html_safe() %></p>
          </div>

          <div class="post">
            <%= form_with model: @comment, local: true do |form| %>
            <%= form.hidden_field :user_id, :value => current_user.id %>
            <%= form.hidden_field :post_id, :value => post.id %>
            <%= form.text_area :content, placeholder: "add a comment...", :class => "post-content" %><br/>
            <small><em>Powered by Markdown</em></small> <br>
            <%= form.submit "Comment", :class => "submit" %>


        <% end %>

        <details>
          <summary >Comments</summary>
          <div class="reverse-post">
          <% post.comments.each do |comment| %>
            <div class="">
              <div class="posts">
                <div class="post">

                  <%= image_tag User.find(comment.user_id).gravatar_url, :class => "mini-avatar" %>
                  <span><em><%= User.find(comment.user_id).username %></em></span>
                  <p><%= @markdown.render(comment.content).html_safe() %></p>
                  </div>

                </div>
              </div>
            <% end %>
          </div>


          </div>
        </details>

    </div>
    <% end %>

  </div>
  <% end %>




  </div>
</div>
</div>
  <% end %>
  <% end %>
<!--
  <div>
    <img src="http://via.placeholder.com/250x250" class="mini-img">
  </div>
  <div>
    <img src="http://via.placeholder.com/250x250" class="mini-img">
  </div>
  <div>
    <img src="http://via.placeholder.com/250x250" class="mini-img">
  </div>
  <div>
    <img src="http://via.placeholder.com/250x250" class="mini-img">
  </div>
  -->

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>