config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root "home#index"
  resources :home
  resources :comments
  resources :games
  resources :posts
  resources :users

  get "/games/show/:name" => "games#show", as: "show_game"
  get "/games/results" => "games#result", as: "game_result"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :game, required: false
  has_many :comments


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {})
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:id])
  end

  def edit
  end

  def destroy
  end

  def update
  end

  def create
    @post = Post.new(post_params)
    @game = @post.game_id

    if @post.save
      flash[:info] = "post submitted"
      redirect_to game_path(@game)
    else
      flash[:error] = "Something went wrong, please try again"
      redirect_to new_post_path
    end
  end

  def new
    @post = Post.new
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :user_id, :game_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<%= form_with model: @post, local: true do |form| %>
    <%= form.text_field :title, placeholder: "title" %><br />
    <%= form.hidden_field :user_id, :value => current_user.id %><br />
    <%= form.text_area :content, placeholder: "content" %>
    <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<% @posts.each do |post| %>
    <li>
        <strong><%= post.title %></strong><br />
        <em><%= User.find(post.user_id).username %></em><br />
        <%= @markdown.render(post.content).html_safe() %><br />

        <%= link_to "Edit", edit_post_path(post.id) %>
        <%= link_to "Show", post_path(post.id) %>
        <%= link_to "Delete", post_path(post.id), method: :delete %>
    <li>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_with model: @post do |form| %>
    <%= form.text_field :title, placeholder: "title" %><br />
    <%= form.text_area :content, placeholder: "content" %>
    <%= form.hidden_field :user_id, :value => current_user.id %><br />
    <%= form.submit %>


    <%= link_to 'Back', posts_path %>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<%= @post.title %><br />
<%= @post.content%>

<%= link_to "Edit", edit_post_path(@post.id) %>
<%= link_to "Delete", post_path(@post.id), method: :delete %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>